[package]
name = "match-maker"
version = "0.0.1"
edition = "2024"
description = "A fuzzy finder for the terminal, powered by nucleo"
repository = "https://github.com/Squirreljetpack/matchmaker"
license-file = "LICENSE"

[dependencies]
ansi-to-tui = "7.0.0"
anyhow = "1.0.100"
atty = "0.2.14"
bitflags = "2.10.0"
boxcar = "0.2.14"
clap = { version = "4.5.51", features = ["derive"] }
crokey = "1.3.0"
crossterm = { version = "0.29.0", features = ["event-stream", "serde", "use-dev-tty"] }
dirs = "6.0.0"
env_logger = "0.11.8"
futures = "0.3.31"
indexmap = "2.12.0"
log = "0.4"
# nix = { version = "0.30.1", features = ["term"] }
nucleo = "0.5.0"
paste = "1.0.15"
phf = { version = "0.13.1", features = ["macros", "phf_macros"] }
ratatui = { version = "0.29.0", features = ["serde"] }
# rayon = "1.11.0"
regex = "1.12.2"
rustc-hash = "2.1.1"
serde = "1.0.228"
strum = "0.27.2"
strum_macros = "0.27.2"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
toml = "0.9.8"
unicode-segmentation = "1.12.0"
unicode-width = "^0.2.0"

[lib]
name = "matchmaker"
path = "src/lib.rs"

[[example]]
name = "basic"
path = "examples/basic.rs"

[[example]]
name = "frecency"
path = "examples/frecency.rs"

[[example]]
name = "ripgrep"
path = "examples/ripgrep.rs"

