[tui]

[ui]

[input]

[results]
wrap = true

[previewer]
try_lossy = false

[preview]
show = true
wrap = true

[[preview.layout]]
command = "bat --binary no-printing --color=always {} || eza --color=always --color=always -T -L 2 {}"
side = "right"
percentage = 40
min = 30
max = 120

[[preview.layout]]
side = "top"
percentage = 50
min = 5
max = 50

[binds]
# UI
"ctrl-c" = "Quit"
"esc" = "Quit"
"enter" = "Accept"
"ctrl-a" = "CycleAll"
"tab" = ["Toggle", "Down"]
"shift-backtab" = ["Toggle", "Up"]

# Edit
"right" = "ForwardChar"
"left" = "BackwardChar"
"ctrl-right" = "ForwardWord"
"ctrl-left" = "BackwardWord"
"backspace" = "DeleteChar"
"ctrl-h" = "DeleteWord"
"ctrl-u" = "Cancel"
"alt-a" = "InputPos(0)"

# Navigation
"up" = "Up"
"down" = "Down"
"pageup" = "Up(10)"
"pagedown" = "Down(10)"
"shift-up" = "PreviewUp"
"shift-down" = "PreviewDown"
"ctrl-shift-up" = "PreviewHalfPageUp"
"ctrl-shift-down" = "PreviewHalfPageDown"

# Preview
"scrollup" = "Up"
"scrolldown" = "Down"
"shift+scrollup" = "PreviewUp"
"shift+scrolldown" = "PreviewDown"
"?" = "SwitchPreview"
"shift-?" = "SwitchPreview"
"alt-h" = "Help"
"alt-1" = "Pos(0)"

# Programmable
"ctrl-l" = "Execute(eval $FZF_PREVIEW_COMMAND | $PAGER)"
"ctrl-o" = "Execute($EDITOR {})"
"alt-o" = "Become($EDITOR {})"
"ctrl-r" = "Reload(find . -type f)"

[matcher]
select_1 = false
default_command = "fd --strip-cwd-prefix"